package com.example.dao;

import java.util.List;

import com.example.entity.GoodsInfo;

public interface IGoodsInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_info
     *
     * @mbggenerated
     */
    int insert(GoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_info
     *
     * @mbggenerated
     */
    int insertSelective(GoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_info
     *
     * @mbggenerated
     */
    GoodsInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsInfo record);

	List<com.example.vo.GoodsInfo> queryAll();
}