package com.example.entity;

public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.shouhuoren
     *
     * @mbggenerated
     */
    private String shouhuoren;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.isdefault
     *
     * @mbggenerated
     */
    private String isdefault;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.id
     *
     * @return the value of t_address.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.id
     *
     * @param id the value for t_address.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.shouhuoren
     *
     * @return the value of t_address.shouhuoren
     *
     * @mbggenerated
     */
    public String getShouhuoren() {
        return shouhuoren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.shouhuoren
     *
     * @param shouhuoren the value for t_address.shouhuoren
     *
     * @mbggenerated
     */
    public void setShouhuoren(String shouhuoren) {
        this.shouhuoren = shouhuoren == null ? null : shouhuoren.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.phone
     *
     * @return the value of t_address.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.phone
     *
     * @param phone the value for t_address.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.address
     *
     * @return the value of t_address.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.address
     *
     * @param address the value for t_address.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.userid
     *
     * @return the value of t_address.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.userid
     *
     * @param userid the value for t_address.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.isdefault
     *
     * @return the value of t_address.isdefault
     *
     * @mbggenerated
     */
    public String getIsdefault() {
        return isdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.isdefault
     *
     * @param isdefault the value for t_address.isdefault
     *
     * @mbggenerated
     */
    public void setIsdefault(String isdefault) {
        this.isdefault = isdefault == null ? null : isdefault.trim();
    }
    
	public Address(String shouhuoren, String phone, String address, int userid) {
		super();
		this.shouhuoren = shouhuoren;
		this.phone = phone;
		this.address = address;
		this.userid = userid;
	}
	public Address() {
		super();
	}
	@Override
	public String toString() {
		return "Address [id=" + id + ", shouhuoren=" + shouhuoren + ", phone="
				+ phone + ", address=" + address + ", userid=" + userid
				+ ", isdefault=" + isdefault + "]";
	}
}