package com.example.entity;

public class GoodsInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_description
     *
     * @mbggenerated
     */
    private String goodsDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_pic
     *
     * @mbggenerated
     */
    private String goodsPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_price
     *
     * @mbggenerated
     */
    private Double goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_stock
     *
     * @mbggenerated
     */
    private Integer goodsStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_price_off
     *
     * @mbggenerated
     */
    private Double goodsPriceOff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_discount
     *
     * @mbggenerated
     */
    private Double goodsDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_fatherid
     *
     * @mbggenerated
     */
    private Integer goodsFatherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_parentid
     *
     * @mbggenerated
     */
    private Integer goodsParentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.isdelete
     *
     * @mbggenerated
     */
    private String isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.id
     *
     * @return the value of t_goods_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.id
     *
     * @param id the value for t_goods_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_name
     *
     * @return the value of t_goods_info.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_name
     *
     * @param goodsName the value for t_goods_info.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_description
     *
     * @return the value of t_goods_info.goods_description
     *
     * @mbggenerated
     */
    public String getGoodsDescription() {
        return goodsDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_description
     *
     * @param goodsDescription the value for t_goods_info.goods_description
     *
     * @mbggenerated
     */
    public void setGoodsDescription(String goodsDescription) {
        this.goodsDescription = goodsDescription == null ? null : goodsDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_pic
     *
     * @return the value of t_goods_info.goods_pic
     *
     * @mbggenerated
     */
    public String getGoodsPic() {
        return goodsPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_pic
     *
     * @param goodsPic the value for t_goods_info.goods_pic
     *
     * @mbggenerated
     */
    public void setGoodsPic(String goodsPic) {
        this.goodsPic = goodsPic == null ? null : goodsPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_price
     *
     * @return the value of t_goods_info.goods_price
     *
     * @mbggenerated
     */
    public Double getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_price
     *
     * @param goodsPrice the value for t_goods_info.goods_price
     *
     * @mbggenerated
     */
    public void setGoodsPrice(Double goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_stock
     *
     * @return the value of t_goods_info.goods_stock
     *
     * @mbggenerated
     */
    public Integer getGoodsStock() {
        return goodsStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_stock
     *
     * @param goodsStock the value for t_goods_info.goods_stock
     *
     * @mbggenerated
     */
    public void setGoodsStock(Integer goodsStock) {
        this.goodsStock = goodsStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_price_off
     *
     * @return the value of t_goods_info.goods_price_off
     *
     * @mbggenerated
     */
    public Double getGoodsPriceOff() {
        return goodsPriceOff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_price_off
     *
     * @param goodsPriceOff the value for t_goods_info.goods_price_off
     *
     * @mbggenerated
     */
    public void setGoodsPriceOff(Double goodsPriceOff) {
        this.goodsPriceOff = goodsPriceOff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_discount
     *
     * @return the value of t_goods_info.goods_discount
     *
     * @mbggenerated
     */
    public Double getGoodsDiscount() {
        return goodsDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_discount
     *
     * @param goodsDiscount the value for t_goods_info.goods_discount
     *
     * @mbggenerated
     */
    public void setGoodsDiscount(Double goodsDiscount) {
        this.goodsDiscount = goodsDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_fatherid
     *
     * @return the value of t_goods_info.goods_fatherid
     *
     * @mbggenerated
     */
    public Integer getGoodsFatherid() {
        return goodsFatherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_fatherid
     *
     * @param goodsFatherid the value for t_goods_info.goods_fatherid
     *
     * @mbggenerated
     */
    public void setGoodsFatherid(Integer goodsFatherid) {
        this.goodsFatherid = goodsFatherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_parentid
     *
     * @return the value of t_goods_info.goods_parentid
     *
     * @mbggenerated
     */
    public Integer getGoodsParentid() {
        return goodsParentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_parentid
     *
     * @param goodsParentid the value for t_goods_info.goods_parentid
     *
     * @mbggenerated
     */
    public void setGoodsParentid(Integer goodsParentid) {
        this.goodsParentid = goodsParentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.isdelete
     *
     * @return the value of t_goods_info.isdelete
     *
     * @mbggenerated
     */
    public String getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.isdelete
     *
     * @param isdelete the value for t_goods_info.isdelete
     *
     * @mbggenerated
     */
    public void setIsdelete(String isdelete) {
        this.isdelete = isdelete == null ? null : isdelete.trim();
    }

	@Override
	public String toString() {
		return "GoodsInfo [id=" + id + ", goodsName=" + goodsName + ", goodsDescription=" + goodsDescription
				+ ", goodsPic=" + goodsPic + ", goodsPrice=" + goodsPrice + ", goodsStock=" + goodsStock
				+ ", goodsPriceOff=" + goodsPriceOff + ", goodsDiscount=" + goodsDiscount + ", goodsFatherid="
				+ goodsFatherid + ", goodsParentid=" + goodsParentid + ", isdelete=" + isdelete + "]";
	}

	public GoodsInfo(Integer id, String goodsName, String goodsDescription, String goodsPic, Double goodsPrice,
			Integer goodsStock, Double goodsPriceOff, Double goodsDiscount, Integer goodsFatherid,
			Integer goodsParentid, String isdelete) {
		super();
		this.id = id;
		this.goodsName = goodsName;
		this.goodsDescription = goodsDescription;
		this.goodsPic = goodsPic;
		this.goodsPrice = goodsPrice;
		this.goodsStock = goodsStock;
		this.goodsPriceOff = goodsPriceOff;
		this.goodsDiscount = goodsDiscount;
		this.goodsFatherid = goodsFatherid;
		this.goodsParentid = goodsParentid;
		this.isdelete = isdelete;
	}

	public GoodsInfo() {
		super();
	}
	
}