package com.example.entity;

public class GoodType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_type.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_type.parentId
     *
     * @mbggenerated
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_type.pic
     *
     * @mbggenerated
     */
    private String pic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_type.id
     *
     * @return the value of t_goods_type.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_type.id
     *
     * @param id the value for t_goods_type.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_type.name
     *
     * @return the value of t_goods_type.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_type.name
     *
     * @param name the value for t_goods_type.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_type.parentId
     *
     * @return the value of t_goods_type.parentId
     *
     * @mbggenerated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_type.parentId
     *
     * @param parentid the value for t_goods_type.parentId
     *
     * @mbggenerated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_type.pic
     *
     * @return the value of t_goods_type.pic
     *
     * @mbggenerated
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_type.pic
     *
     * @param pic the value for t_goods_type.pic
     *
     * @mbggenerated
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

	@Override
	public String toString() {
		return "GoodType [id=" + id + ", name=" + name + ", parentid=" + parentid + ", pic=" + pic + "]";
	}

	public GoodType(Integer id, String name, Integer parentid, String pic) {
		super();
		this.id = id;
		this.name = name;
		this.parentid = parentid;
		this.pic = pic;
	}

	public GoodType() {
		super();
	}
    
}